# Generated by Django 4.2.4 on 2023-08-10 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(blank=True, max_length=250, verbose_name="Question")),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "question",
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("choice", models.CharField(blank=True, max_length=250, verbose_name="Choice")),
                ("votes", models.IntegerField()),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="polls.poll")),
            ],
        ),
    ]
